Repository DaengPlace/BackEnd, pull requests merged in 2024-12, with the labels that each got.

#53 Feat/revise review
  src/main/java/com/mycom/backenddaengplace/review/controller/ReviewController.java
  src/main/java/com/mycom/backenddaengplace/review/domain/Review.java
  src/main/java/com/mycom/backenddaengplace/review/dto/response/MemberReviewResponse.java
  src/main/java/com/mycom/backenddaengplace/review/exception/ReviewException.java
  src/main/java/com/mycom/backenddaengplace/review/service/ReviewService.java
  src/main/resources/db/data.sql
Labels: 🔨 Refactor, ✨ Feature

#57 Review auth
  src/main/java/com/mycom/backenddaengplace/auth/config/SecurityConfig.java
  src/main/java/com/mycom/backenddaengplace/auth/config/WebConfig.java
  src/main/java/com/mycom/backenddaengplace/auth/controller/ApiTestController.java
  src/main/java/com/mycom/backenddaengplace/auth/controller/HomeController.java
  src/main/java/com/mycom/backenddaengplace/auth/dto/CustomOAuth2User.java
  src/main/java/com/mycom/backenddaengplace/auth/dto/CustomUserDetails.java
  src/main/java/com/mycom/backenddaengplace/auth/jwt/JWTFilter.java
  src/main/java/com/mycom/backenddaengplace/auth/jwt/JWTUtil.java
  src/main/java/com/mycom/backenddaengplace/auth/service/CustomOAuth2UserService.java
  src/main/java/com/mycom/backenddaengplace/review/controller/ReviewController.java
  src/main/java/com/mycom/backenddaengplace/review/controller/ReviewLikeController.java
  src/main/java/com/mycom/backenddaengplace/review/dto/request/ReviewRequest.java
  src/main/java/com/mycom/backenddaengplace/review/service/ReviewLikeService.java
  src/main/java/com/mycom/backenddaengplace/review/service/ReviewService.java
  src/main/resources/application.yml
Labels: ⚙ Setting, 🔨 Refactor, 🥰 Accessibility, ✨ Feature

#60 🔀 내가 작성한 리뷰 목록 조회 수정
  src/main/java/com/mycom/backenddaengplace/review/controller/ReviewController.java
  src/main/java/com/mycom/backenddaengplace/review/service/ReviewService.java
Labels: 🔨 Refactor, ✨ Feature

#61 🔀 리뷰 삭제 코드 수정
  src/main/java/com/mycom/backenddaengplace/review/service/ReviewService.java
Labels: 🔨 Refactor

#62 :recycle: Favorite, Member auth 추가
  src/main/java/com/mycom/backenddaengplace/favorite/controller/FavoriteController.java
  src/main/java/com/mycom/backenddaengplace/favorite/dto/request/FavoriteDeleteRequest.java
  src/main/java/com/mycom/backenddaengplace/favorite/dto/request/FavoriteRequest.java
  src/main/java/com/mycom/backenddaengplace/favorite/dto/request/FavoritesRequest.java
  src/main/java/com/mycom/backenddaengplace/favorite/service/FavoriteService.java
  src/main/java/com/mycom/backenddaengplace/member/controller/MemberController.java
  src/main/java/com/mycom/backenddaengplace/member/domain/Member.java
  src/main/java/com/mycom/backenddaengplace/member/dto/request/MemberUpdateRequest.java
  src/main/java/com/mycom/backenddaengplace/member/service/MemberService.java
Labels: 🔨 Refactor, ✨ Feature

#64 Feat/get trait question
  src/main/java/com/mycom/backenddaengplace/trait/controller/TraitController.java
  src/main/java/com/mycom/backenddaengplace/trait/domain/MemberTraitResponse.java
  src/main/java/com/mycom/backenddaengplace/trait/domain/MemberTraitResponseId.java
  src/main/java/com/mycom/backenddaengplace/trait/domain/TraitAnswer.java
  src/main/java/com/mycom/backenddaengplace/trait/domain/TraitQuestion.java
  src/main/java/com/mycom/backenddaengplace/trait/dto/response/TraitAnswerResponse.java
  src/main/java/com/mycom/backenddaengplace/trait/dto/response/TraitQuestionResponse.java
  src/main/java/com/mycom/backenddaengplace/trait/enums/QuestionTarget.java
  src/main/java/com/mycom/backenddaengplace/trait/repository/TraitQuestionRepository.java
  src/main/java/com/mycom/backenddaengplace/trait/service/TraitService.java
Labels: 🔨 Refactor, ✨ Feature

#67 Feat/save trait result
  src/main/java/com/mycom/backenddaengplace/trait/controller/TraitController.java
  src/main/java/com/mycom/backenddaengplace/trait/domain/MemberTraitResponse.java
  src/main/java/com/mycom/backenddaengplace/trait/dto/request/MemberTraitResponseRequest.java
  src/main/java/com/mycom/backenddaengplace/trait/dto/request/MemberTraitResponseRequestList.java
  src/main/java/com/mycom/backenddaengplace/trait/exception/TraitAnswerNotFoundException.java
  src/main/java/com/mycom/backenddaengplace/trait/exception/TraitQuestionNotFoundException.java
  src/main/java/com/mycom/backenddaengplace/trait/repository/MemberTraitResponseRepository.java
  src/main/java/com/mycom/backenddaengplace/trait/repository/TraitAnswerRepository.java
  src/main/java/com/mycom/backenddaengplace/trait/service/MemberTraitService.java
Labels: 🔨 Refactor, ✨ Feature

#73 Refactor/place entity
  src/main/java/com/mycom/backenddaengplace/place/domain/Address.java
  src/main/java/com/mycom/backenddaengplace/place/domain/OperationHour.java
  src/main/java/com/mycom/backenddaengplace/place/domain/Place.java
  src/main/java/com/mycom/backenddaengplace/place/dto/request/SearchCriteria.java
  src/main/java/com/mycom/backenddaengplace/place/dto/response/OperationHourDto.java
  src/main/java/com/mycom/backenddaengplace/place/dto/response/PlaceDetailResponse.java
  src/main/java/com/mycom/backenddaengplace/place/dto/response/PlaceDto.java
  src/main/java/com/mycom/backenddaengplace/place/enums/Category.java
  src/main/java/com/mycom/backenddaengplace/place/enums/OperationStatus.java
  src/main/java/com/mycom/backenddaengplace/place/enums/WeatherType.java
  src/main/java/com/mycom/backenddaengplace/place/repository/PlaceQueryRepository.java
  src/main/java/com/mycom/backenddaengplace/place/service/PlaceService.java
Labels: 🔨 Refactor, ✨ Feature

#76 Refactor/place
  src/main/java/com/mycom/backenddaengplace/place/dto/response/PlaceDetailResponse.java
  src/main/java/com/mycom/backenddaengplace/place/repository/OperationHourRepository.java
  src/main/java/com/mycom/backenddaengplace/place/repository/PlaceQueryRepository.java
  src/main/java/com/mycom/backenddaengplace/place/service/PlaceService.java
  src/main/resources/application.yml
Labels: 🔨 Refactor, ✨ Feature

#84 Feat/social login
  build.gradle
  src/main/java/com/mycom/backenddaengplace/auth/config/SecurityConfig.java
  src/main/java/com/mycom/backenddaengplace/auth/config/WebConfig.java
  src/main/java/com/mycom/backenddaengplace/auth/controller/LogoutController.java
  src/main/java/com/mycom/backenddaengplace/auth/controller/ReissueController.java
  src/main/java/com/mycom/backenddaengplace/auth/controller/TokenController.java
  src/main/java/com/mycom/backenddaengplace/auth/controller/UserInfoController.java
  src/main/java/com/mycom/backenddaengplace/auth/dto/response/GoogleResponse.java
  src/main/java/com/mycom/backenddaengplace/auth/dto/response/KakaoResponse.java
  src/main/java/com/mycom/backenddaengplace/auth/dto/response/OAuth2Response.java
  src/main/java/com/mycom/backenddaengplace/auth/handler/CustomSuccessHandler.java
  src/main/java/com/mycom/backenddaengplace/auth/interceptor/AuthorizationInterceptor.java
  src/main/java/com/mycom/backenddaengplace/auth/service/CustomOAuth2UserService.java
  src/main/java/com/mycom/backenddaengplace/ocrtest/controller/OcrController.java
  src/main/java/com/mycom/backenddaengplace/ocrtest/controller/ReceiptOCRController.java
  src/main/resources/application-email.yml
  src/main/resources/application-security.yml
Labels: 🔨 Refactor, ✨ Feature

#104 CORS Error Bug Fix
  src/main/java/com/mycom/backenddaengplace/auth/config/SecurityConfig.java
  src/main/java/com/mycom/backenddaengplace/auth/config/WebConfig.java
Labels: 🐞 BugFix, 🔨 Refactor

#105 Feat/get pet trait
  src/main/java/com/mycom/backenddaengplace/pet/repository/PetRepository.java
  src/main/java/com/mycom/backenddaengplace/trait/controller/TraitController.java
  src/main/java/com/mycom/backenddaengplace/trait/dto/response/PetTraitResult.java
  src/main/java/com/mycom/backenddaengplace/trait/dto/response/TraitResult.java
  src/main/java/com/mycom/backenddaengplace/trait/dto/response/TraitResultResponse.java
  src/main/java/com/mycom/backenddaengplace/trait/repository/MemberTraitResponseRepository.java
  src/main/java/com/mycom/backenddaengplace/trait/repository/PetTraitResponseRepository.java
  src/main/java/com/mycom/backenddaengplace/trait/service/TraitService.java
Labels: ✨ Feature

#113 Refactor/review
  src/main/java/com/mycom/backenddaengplace/review/controller/ReviewController.java
  src/main/java/com/mycom/backenddaengplace/review/domain/BasicTag.java
  src/main/java/com/mycom/backenddaengplace/review/domain/BasicTagCount.java
  src/main/java/com/mycom/backenddaengplace/review/domain/BasicTagCountId.java
  src/main/java/com/mycom/backenddaengplace/review/domain/Review.java
  src/main/java/com/mycom/backenddaengplace/review/dto/response/MemberReviewResponse.java
  src/main/java/com/mycom/backenddaengplace/review/dto/response/ReviewResponse.java
  src/main/java/com/mycom/backenddaengplace/review/repository/ReviewRepository.java
  src/main/java/com/mycom/backenddaengplace/review/service/ReviewService.java
  src/main/java/com/mycom/backenddaengplace/trait/domain/TraitTagCount.java
  src/main/java/com/mycom/backenddaengplace/trait/dto/response/TraitTagCountResponse.java
  src/main/java/com/mycom/backenddaengplace/trait/repository/TraitTagCountRepository.java
  src/main/java/com/mycom/backenddaengplace/trait/repository/TraitTagRepository.java
Labels: 🔨 Refactor, ✨ Feature

#122 Refactor Review
  src/main/java/com/mycom/backenddaengplace/review/controller/ReviewController.java
  src/main/java/com/mycom/backenddaengplace/review/service/ReviewService.java
Labels: 🔨 Refactor, 📬 API

#128 :recycle: #127 json 형식 변환
  src/main/java/com/mycom/backenddaengplace/auth/controller/GoogleCallbackController.java
  src/main/java/com/mycom/backenddaengplace/auth/controller/KakaoCallbackController.java
Labels: ⚙ Setting, 🔨 Refactor

#130 [Refactor] 소셜로그인 토큰 발급
  src/main/java/com/mycom/backenddaengplace/auth/controller/GoogleAuthController.java
  src/main/java/com/mycom/backenddaengplace/auth/controller/GoogleCallbackController.java
  src/main/java/com/mycom/backenddaengplace/auth/controller/KakaoAuthController.java
  src/main/java/com/mycom/backenddaengplace/auth/controller/KakaoCallbackController.java
  src/main/java/com/mycom/backenddaengplace/auth/controller/UserInfoController.java
  src/main/java/com/mycom/backenddaengplace/auth/dto/UserDTO.java
  src/main/java/com/mycom/backenddaengplace/auth/dto/response/GoogleResponse.java
  src/main/java/com/mycom/backenddaengplace/auth/handler/CustomSuccessHandler.java
  src/main/java/com/mycom/backenddaengplace/auth/service/CustomOAuth2UserService.java
  src/main/resources/application-security.yml
Labels: ⚙ Setting, 🔨 Refactor

#131 Pet Trait
  src/main/java/com/mycom/backenddaengplace/place/dto/response/PopularPlaceResponse.java
  src/main/java/com/mycom/backenddaengplace/place/repository/PlaceQueryRepository.java
  src/main/java/com/mycom/backenddaengplace/trait/controller/RecommendationController.java
  src/main/java/com/mycom/backenddaengplace/trait/repository/PlaceRecommendationQueryRepository.java
  src/main/java/com/mycom/backenddaengplace/trait/service/RecommendationService.java
Labels: ✨ Feature

#135 Setting Redis
  src/main/resources/application-dev.yml
Labels: 🔨 Refactor, 📬 API

#137 :recycle: #136 회원가입 추가
  src/main/java/com/mycom/backenddaengplace/auth/handler/CustomSuccessHandler.java
Labels: 🔨 Refactor, 📬 API

#138 🔀 Member trait
  src/main/java/com/mycom/backenddaengplace/trait/controller/RecommendationController.java
  src/main/java/com/mycom/backenddaengplace/trait/repository/PlaceRecommendationQueryRepository.java
  src/main/java/com/mycom/backenddaengplace/trait/service/RecommendationService.java
Labels: ✨ Feature

#140 Refactor Member Register
  src/main/java/com/mycom/backenddaengplace/auth/config/SecurityConfig.java
  src/main/java/com/mycom/backenddaengplace/auth/config/WebConfig.java
  src/main/java/com/mycom/backenddaengplace/auth/email/RedisEmailAuthentication.java
  src/main/java/com/mycom/backenddaengplace/common/config/EmailConfig.java
  src/main/java/com/mycom/backenddaengplace/common/config/RedisConfig.java
  src/main/java/com/mycom/backenddaengplace/member/controller/MemberController.java
  src/main/java/com/mycom/backenddaengplace/member/enums/Gender.java
  src/main/java/com/mycom/backenddaengplace/member/service/EmailService.java
Labels: 🔨 Refactor, 📬 API

#142 견종 등록 리팩토링
  src/main/java/com/mycom/backenddaengplace/pet/dto/request/BasePetRequest.java
  src/main/java/com/mycom/backenddaengplace/pet/repository/BreedTypeRepository.java
  src/main/java/com/mycom/backenddaengplace/pet/service/BreedService.java
  src/main/java/com/mycom/backenddaengplace/pet/service/PetService.java
Labels: 🔨 Refactor, 📬 API

#144 견종 도메인 리팩토링
  src/main/java/com/mycom/backenddaengplace/pet/repository/BreedTypeRepository.java
  src/main/java/com/mycom/backenddaengplace/pet/service/BreedService.java
Labels: 🔨 Refactor, 📬 API

#146 :recycle: #145 리다이렉트 주소 변경
  src/main/java/com/mycom/backenddaengplace/auth/handler/CustomSuccessHandler.java
Labels: 🔨 Refactor, 📬 API

#154 회원 로직 리팩토링
  src/main/java/com/mycom/backenddaengplace/member/controller/MemberController.java
  src/main/java/com/mycom/backenddaengplace/member/dto/request/MemberRegisterRequest.java
  src/main/java/com/mycom/backenddaengplace/member/repository/MemberRepository.java
  src/main/java/com/mycom/backenddaengplace/member/service/MemberService.java
Labels: 🔨 Refactor, 📬 API

#155 Image Upload
  build.gradle
  src/main/java/com/mycom/backenddaengplace/common/config/S3Config.java
  src/main/java/com/mycom/backenddaengplace/common/service/S3ImageService.java
  src/main/java/com/mycom/backenddaengplace/member/controller/MemberController.java
  src/main/java/com/mycom/backenddaengplace/member/service/MemberService.java
  src/main/java/com/mycom/backenddaengplace/review/controller/ReviewController.java
  src/main/java/com/mycom/backenddaengplace/review/domain/MediaFile.java
  src/main/java/com/mycom/backenddaengplace/review/dto/response/ReviewResponse.java
  src/main/java/com/mycom/backenddaengplace/review/service/ReviewService.java
  src/main/resources/application-security.yml
Labels: 🔨 Refactor, 📬 API, ✨ Feature

#157 🔀Refactor/place
  src/main/java/com/mycom/backenddaengplace/favorite/repository/FavoriteRepository.java
  src/main/java/com/mycom/backenddaengplace/place/controller/PlaceController.java
  src/main/java/com/mycom/backenddaengplace/place/dto/response/PlaceDetailResponse.java
  src/main/java/com/mycom/backenddaengplace/place/dto/response/PlaceDto.java
  src/main/java/com/mycom/backenddaengplace/place/repository/PlaceQueryRepository.java
  src/main/java/com/mycom/backenddaengplace/place/service/PlaceService.java
Labels: 🔨 Refactor, ✨ Feature

#163 :recycle: #162 생년월일 8자리
  src/main/java/com/mycom/backenddaengplace/member/dto/request/MemberRegisterRequest.java
  src/main/java/com/mycom/backenddaengplace/member/dto/request/MemberUpdateRequest.java
  src/main/java/com/mycom/backenddaengplace/member/service/MemberService.java
  src/main/java/com/mycom/backenddaengplace/pet/dto/request/BasePetRequest.java
  src/main/java/com/mycom/backenddaengplace/pet/dto/request/PetReviseRequest.java
  src/main/java/com/mycom/backenddaengplace/pet/exception/InvalidBirthDateException.java
  src/main/java/com/mycom/backenddaengplace/pet/service/PetService.java
Labels: 🔨 Refactor, 📬 API

#169 🔀 장소 상세 조회시 리뷰 이미지 불러오기
  src/main/java/com/mycom/backenddaengplace/place/service/PlaceService.java
Labels: 🔨 Refactor

#171 회원 탈퇴 기능 구현
  src/main/java/com/mycom/backenddaengplace/member/controller/MemberController.java
  src/main/java/com/mycom/backenddaengplace/member/domain/Member.java
  src/main/java/com/mycom/backenddaengplace/member/dto/response/BaseMemberResponse.java
  src/main/java/com/mycom/backenddaengplace/member/service/MemberService.java
Labels: 📬 API, ✨ Feature

#175 🔀 불필요한 코드 제거
  src/main/java/com/mycom/backenddaengplace/favorite/controller/FavoriteController.java
  src/main/java/com/mycom/backenddaengplace/favorite/domain/Recommend.java
  src/main/java/com/mycom/backenddaengplace/favorite/dto/response/FavoriteDeleteResponse.java
  src/main/java/com/mycom/backenddaengplace/favorite/dto/response/FavoritesResponse.java
  src/main/java/com/mycom/backenddaengplace/favorite/repository/FavoriteRepository.java
  src/main/java/com/mycom/backenddaengplace/favorite/service/FavoriteService.java
  src/main/java/com/mycom/backenddaengplace/member/repository/MemberRepository.java
  src/main/java/com/mycom/backenddaengplace/ocr/controller/OcrController.java
  src/main/java/com/mycom/backenddaengplace/ocr/controller/ReceiptOCRController.java
  src/main/java/com/mycom/backenddaengplace/ocr/service/OcrService.java
  src/main/java/com/mycom/backenddaengplace/ocr/service/OcrServiceImpl.java
  src/main/java/com/mycom/backenddaengplace/ocrtest/CustomException.java
  src/main/java/com/mycom/backenddaengplace/ocrtest/controller/OcrResultProcessor.java
  src/main/java/com/mycom/backenddaengplace/ocrtest/entity/OcrResult.java
  src/main/java/com/mycom/backenddaengplace/ocrtest/repository/OcrResultRepository.java
  src/main/java/com/mycom/backenddaengplace/ocrtest/service/OCRProcessor.java
  src/main/java/com/mycom/backenddaengplace/place/domain/PlaceVisit.java
  src/main/java/com/mycom/backenddaengplace/place/domain/PlaceVisitId.java
  src/main/java/com/mycom/backenddaengplace/place/dto/request/SearchCriteria.java
  src/main/java/com/mycom/backenddaengplace/place/dto/response/AgeGenderPlaceResponse.java
  src/main/java/com/mycom/backenddaengplace/place/dto/response/PlaceDetailResponse.java
  src/main/java/com/mycom/backenddaengplace/place/dto/response/TodayOperationHourDto.java
  src/main/java/com/mycom/backenddaengplace/place/repository/OperationHourRepository.java
  src/main/java/com/mycom/backenddaengplace/place/service/PlaceService.java
  src/main/java/com/mycom/backenddaengplace/review/controller/ReviewLikeController.java
  src/main/java/com/mycom/backenddaengplace/review/repository/ReviewRepository.java
  src/main/java/com/mycom/backenddaengplace/trait/domain/PetTraitResponseId.java
Labels: 🔨 Refactor

#177 이미지 수정 리팩토링
  src/main/java/com/mycom/backenddaengplace/review/controller/ReviewController.java
  src/main/java/com/mycom/backenddaengplace/review/service/ReviewService.java
Labels: 🔨 Refactor, 📬 API

#179 이메일 인증 번호 유효 시간 수정
  src/main/java/com/mycom/backenddaengplace/member/service/EmailService.java
Labels: 🔨 Refactor

#188 반려견 성향 추천(인증된 사용자의 반려견 기준으로 추천)
  src/main/java/com/mycom/backenddaengplace/trait/controller/RecommendationController.java
  src/main/java/com/mycom/backenddaengplace/trait/exception/UnauthorizedException.java
  src/main/java/com/mycom/backenddaengplace/trait/service/RecommendationService.java
Labels: 🔨 Refactor, 📬 API

#192 프로필 이미지 등록 로직 수정
  src/main/java/com/mycom/backenddaengplace/member/controller/MemberController.java
  src/main/java/com/mycom/backenddaengplace/member/dto/response/BaseMemberResponse.java
  src/main/java/com/mycom/backenddaengplace/member/service/MemberService.java
Labels: 🔨 Refactor, 📬 API

#194 🔀 성향, 추천 리팩토링
  src/main/java/com/mycom/backenddaengplace/trait/controller/TraitController.java
  src/main/java/com/mycom/backenddaengplace/trait/repository/MemberTraitResponseRepository.java
  src/main/java/com/mycom/backenddaengplace/trait/service/MemberTraitService.java
  src/main/java/com/mycom/backenddaengplace/trait/service/RecommendationService.java
Labels: 🔨 Refactor

#196 야외 공간 있는 카페 Best 5 기능 구현
  src/main/java/com/mycom/backenddaengplace/place/controller/PlaceController.java
  src/main/java/com/mycom/backenddaengplace/place/repository/PlaceQueryRepository.java
  src/main/java/com/mycom/backenddaengplace/place/service/PlaceService.java
Labels: 📬 API, ✨ Feature

#200 :recycle: 장소 목록 정렬 기본값을 거리순으로 변경
  src/main/java/com/mycom/backenddaengplace/place/repository/PlaceQueryRepository.java
Labels: 🔨 Refactor

#198 Refactor Profile Modify
  src/main/java/com/mycom/backenddaengplace/member/service/MemberService.java
  src/main/resources/db/data.sql
Labels: 📬 API, ✨ Feature

#202 Refactor/place search
  src/main/java/com/mycom/backenddaengplace/place/repository/PlaceQueryRepository.java
Labels: 🔨 Refactor

#204 :recycle: #203 토큰 저장 변수 변화
  src/main/java/com/mycom/backenddaengplace/auth/controller/LogoutController.java
  src/main/java/com/mycom/backenddaengplace/auth/handler/CustomSuccessHandler.java
Labels: 🔨 Refactor, 📬 API

#207 회원 물리적 삭제 구현
  src/main/java/com/mycom/backenddaengplace/BackEndDaengPlaceApplication.java
  src/main/java/com/mycom/backenddaengplace/favorite/repository/FavoriteRepository.java
  src/main/java/com/mycom/backenddaengplace/member/repository/MemberRepository.java
  src/main/java/com/mycom/backenddaengplace/member/service/MemberService.java
  src/main/java/com/mycom/backenddaengplace/pet/repository/PetRepository.java
  src/main/java/com/mycom/backenddaengplace/review/repository/MediaFileRepository.java
  src/main/java/com/mycom/backenddaengplace/review/repository/ReviewLikeRepository.java
  src/main/java/com/mycom/backenddaengplace/review/repository/ReviewRepository.java
  src/main/java/com/mycom/backenddaengplace/trait/repository/MemberTraitResponseRepository.java
  src/main/java/com/mycom/backenddaengplace/trait/repository/PetTraitResponseRepository.java
Labels: 🔨 Refactor, ✨ Feature

#209 사용자 프로필 수정
  src/main/java/com/mycom/backenddaengplace/member/service/MemberService.java
Labels: 📬 API, ✨ Feature

#211 리뷰에서 사용자 프로필 가져오기
  src/main/java/com/mycom/backenddaengplace/review/dto/response/ReviewResponse.java
Labels: 🔨 Refactor, 📬 API
