Repository DaengPlace/BackEnd, pull requests merged in 2024-11, with the labels that each got.

#18 Review Register
  src/main/java/com/mycom/backenddaengplace/member/exception/MemberNotFoundException.java
  src/main/java/com/mycom/backenddaengplace/member/repository/MemberRepository.java
  src/main/java/com/mycom/backenddaengplace/pet/exception/BreedNotFoundException.java
  src/main/java/com/mycom/backenddaengplace/pet/exception/InvalidBirthDateException.java
  src/main/java/com/mycom/backenddaengplace/pet/exception/PetException.java
  src/main/java/com/mycom/backenddaengplace/place/exception/PlaceNotFoundException.java
  src/main/java/com/mycom/backenddaengplace/place/service/PlaceService.java
  src/main/java/com/mycom/backenddaengplace/review/controller/ReviewController.java
  src/main/java/com/mycom/backenddaengplace/review/dto/request/ReviewRequest.java
  src/main/java/com/mycom/backenddaengplace/review/dto/response/ReviewResponse.java
  src/main/java/com/mycom/backenddaengplace/review/exception/ReviewAlreadyExistsException.java
  src/main/java/com/mycom/backenddaengplace/review/repository/ReviewRepository.java
  src/main/java/com/mycom/backenddaengplace/review/service/ReviewService.java
Labels: 🔨 Refactor, ✨ Feature

#33 feat/pet_crud
  src/main/java/com/mycom/backenddaengplace/pet/controller/PetController.java
  src/main/java/com/mycom/backenddaengplace/pet/domain/BreedType.java
  src/main/java/com/mycom/backenddaengplace/pet/domain/Pet.java
  src/main/java/com/mycom/backenddaengplace/pet/dto/request/BasePetRequest.java
  src/main/java/com/mycom/backenddaengplace/pet/dto/request/PetReviseRequest.java
  src/main/java/com/mycom/backenddaengplace/pet/dto/response/BasePetResponse.java
  src/main/java/com/mycom/backenddaengplace/pet/dto/response/PetDeleteResponse.java
  src/main/java/com/mycom/backenddaengplace/pet/dto/response/PetRegisterResponse.java
  src/main/java/com/mycom/backenddaengplace/pet/exception/PetNotFoundException.java
  src/main/java/com/mycom/backenddaengplace/pet/service/PetService.java
Labels: 🔨 Refactor, ✨ Feature

#37 Popular Place
  src/main/java/com/mycom/backenddaengplace/place/controller/PlaceController.java
  src/main/java/com/mycom/backenddaengplace/place/dto/response/PopularPlaceResponse.java
  src/main/java/com/mycom/backenddaengplace/place/repository/PlaceQueryRepository.java
  src/main/java/com/mycom/backenddaengplace/place/service/PlaceService.java
  src/main/resources/db/data.sql
Labels: 🔨 Refactor, ✨ Feature

#47 :sparkles: 리뷰 삭제 기능 구현
  src/main/java/com/mycom/backenddaengplace/review/controller/ReviewController.java
  src/main/java/com/mycom/backenddaengplace/review/exception/ReviewNotOwnedException.java
  src/main/java/com/mycom/backenddaengplace/review/repository/ReviewRepository.java
  src/main/java/com/mycom/backenddaengplace/review/service/ReviewService.java
Labels: ✨ Feature

#48 Review Like & Review Refactor
  src/main/java/com/mycom/backenddaengplace/member/domain/Member.java
  src/main/java/com/mycom/backenddaengplace/review/controller/ReviewController.java
  src/main/java/com/mycom/backenddaengplace/review/controller/ReviewLikeController.java
  src/main/java/com/mycom/backenddaengplace/review/domain/Review.java
  src/main/java/com/mycom/backenddaengplace/review/domain/ReviewLike.java
  src/main/java/com/mycom/backenddaengplace/review/dto/response/ReviewLikeResponse.java
  src/main/java/com/mycom/backenddaengplace/review/exception/ReviewException.java
  src/main/java/com/mycom/backenddaengplace/review/repository/ReviewLikeRepository.java
  src/main/java/com/mycom/backenddaengplace/review/service/ReviewLikeService.java
Labels: ⚙ Setting, 🔨 Refactor, ✨ Feature
